import typing

HELP: MutState
VERBOSE: MutState

class Formatter:
    def __init__(self) -> None: ...
    def format(self, arg0: object) -> str: ...

class MutInt:
    value: int
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __add__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> MutInt: ...
    def __bool__(self) -> bool: ...
    def __iadd__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> MutInt: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __isub__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> MutInt: ...
    def __sub__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> MutInt: ...

class MutState(MutInt):
    lvalue: int
    def __init__(self, *args, **kwargs) -> None: ...
    def disable(self) -> None: ...
    def enable(self) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def set(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
